"""Variational fruiting-system generator (P0) and M1 coupled cable scenes."""

from __future__ import annotations

from apple_pick_sim.fruiting_system.build import make_fruiting_solver_vbd
from apple_pick_sim.fruiting_system.coupled import (
    CoupledCableScene,
    generate_coupled_cable_scene,
    geometry_fingerprint_coupled,
)
from apple_pick_sim.fruiting_system.params import (
    FruitingSystemParams,
    FixtureArgs,
    GripperProxyConfig,
    PLACEHOLDER_EE_MASS_KG,
    RodParams,
    analytic_apple_mass_kg,
    copy_fruiting_params,
    default_ranges_fixture_path,
    enabled_rod_segments,
    fruiting_params_from_dict,
    fruiting_params_from_json,
    fruiting_params_to_dict,
    fruiting_params_to_json,
    load_ranges,
    params_fingerprint,
    parse_fixture_args,
    perturb_rod_stiffness,
    resolve_fruiting_base_pos,
    resolve_robot_base_pos,
    sample_heterogeneous_params_list,
    sample_params,
    set_rod_bend_stiffness,
    TOPOLOGY_LINEAR_CHAIN,
    TOPOLOGY_T_JUNCTION,
)
from apple_pick_sim.fruiting_system.scene import (
    FruitingSystemScene,
    _build_scene,
    example_collision_pipeline,
    fixed_joint_anchors_world,
    generate_scene,
    geometry_fingerprint,
    iter_fruiting_fixed_joint_indices,
    measure_fruiting_forces,
    run_rollout,
)

from apple_pick_sim.vbd_fixed_joint_wrenches import (
    FixedJointWrenchRecord,
    fixed_joint_wrenches_child_com_vbd,
    iter_fixed_joint_indices,
)

__all__ = [
    "CoupledCableScene",
    "FruitingSystemParams",
    "FruitingSystemScene",
    "FixtureArgs",
    "GripperProxyConfig",
    "PLACEHOLDER_EE_MASS_KG",
    "RodParams",
    "analytic_apple_mass_kg",
    "_build_scene",
    "copy_fruiting_params",
    "enabled_rod_segments",
    "example_collision_pipeline",
    "fixed_joint_anchors_world",
    "fruiting_params_from_dict",
    "fruiting_params_from_json",
    "fruiting_params_to_dict",
    "fruiting_params_to_json",
    "generate_coupled_cable_scene",
    "generate_scene",
    "geometry_fingerprint",
    "geometry_fingerprint_coupled",
    "FixedJointWrenchRecord",
    "fixed_joint_wrenches_child_com_vbd",
    "iter_fruiting_fixed_joint_indices",
    "default_ranges_fixture_path",
    "load_ranges",
    "make_fruiting_solver_vbd",
    "measure_fruiting_forces",
    "params_fingerprint",
    "parse_fixture_args",
    "perturb_rod_stiffness",
    "resolve_fruiting_base_pos",
    "resolve_robot_base_pos",
    "set_rod_bend_stiffness",
    "TOPOLOGY_LINEAR_CHAIN",
    "TOPOLOGY_T_JUNCTION",
    "run_rollout",
    "sample_heterogeneous_params_list",
    "sample_params",
]
